version: "3.8"

services:
  postgres:
    image: postgres:alpine3.18
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: tenderr
    volumes:
      - postgres:/var/lib/postgresql/data
  clickhouse:
    image: clickhouse/clickhouse-server:head-alpine
    ports:
      - "127.0.0.1:8123:8123"
      - "127.0.0.1:9000:9000"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_USER: tenderr
      CLICKHOUSE_PASSWORD: password
    volumes:
      - ./services/classifier/clickhouse/users.d:/etc/clickhouse-server/users.d/
      - ./services/classifier/clickhouse/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - clickhouse:/var/lib/clickhouse/
  grafana:
    image: grafana/grafana:latest
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    volumes:
      - ./services/classifier/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./services/classifier/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./services/classifier/grafana/dashboards:/etc/grafana/dashboards
      - grafana:/var/lib/grafana
    depends_on:
      - clickhouse

volumes:
  postgres:
  clickhouse:
  grafana:
