addr: 127.0.0.1:8080
postgresUrl: postgres://tenderr:password@localhost:5432/tenderr?sslmode=disable
clickhouse:
  addr: localhost:9000
  database: default
  username: tenderr
  password: password
cors:
  enabled: true
  allowedOrigins: "*"
  allowedMethods: "*"
  allowedHeaders: "*"
  allowCredentials: true
logLevel: warn